require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RefenciacontablesController do

  # This should return the minimal set of attributes required to create a valid
  # Refenciacontable. As you add validations to Refenciacontable, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all refenciacontables as @refenciacontables" do
      refenciacontable = Refenciacontable.create! valid_attributes
      get :index
      assigns(:refenciacontables).should eq([refenciacontable])
    end
  end

  describe "GET show" do
    it "assigns the requested refenciacontable as @refenciacontable" do
      refenciacontable = Refenciacontable.create! valid_attributes
      get :show, :id => refenciacontable.id.to_s
      assigns(:refenciacontable).should eq(refenciacontable)
    end
  end

  describe "GET new" do
    it "assigns a new refenciacontable as @refenciacontable" do
      get :new
      assigns(:refenciacontable).should be_a_new(Refenciacontable)
    end
  end

  describe "GET edit" do
    it "assigns the requested refenciacontable as @refenciacontable" do
      refenciacontable = Refenciacontable.create! valid_attributes
      get :edit, :id => refenciacontable.id.to_s
      assigns(:refenciacontable).should eq(refenciacontable)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Refenciacontable" do
        expect {
          post :create, :refenciacontable => valid_attributes
        }.to change(Refenciacontable, :count).by(1)
      end

      it "assigns a newly created refenciacontable as @refenciacontable" do
        post :create, :refenciacontable => valid_attributes
        assigns(:refenciacontable).should be_a(Refenciacontable)
        assigns(:refenciacontable).should be_persisted
      end

      it "redirects to the created refenciacontable" do
        post :create, :refenciacontable => valid_attributes
        response.should redirect_to(Refenciacontable.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved refenciacontable as @refenciacontable" do
        # Trigger the behavior that occurs when invalid params are submitted
        Refenciacontable.any_instance.stub(:save).and_return(false)
        post :create, :refenciacontable => {}
        assigns(:refenciacontable).should be_a_new(Refenciacontable)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Refenciacontable.any_instance.stub(:save).and_return(false)
        post :create, :refenciacontable => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested refenciacontable" do
        refenciacontable = Refenciacontable.create! valid_attributes
        # Assuming there are no other refenciacontables in the database, this
        # specifies that the Refenciacontable created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Refenciacontable.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => refenciacontable.id, :refenciacontable => {'these' => 'params'}
      end

      it "assigns the requested refenciacontable as @refenciacontable" do
        refenciacontable = Refenciacontable.create! valid_attributes
        put :update, :id => refenciacontable.id, :refenciacontable => valid_attributes
        assigns(:refenciacontable).should eq(refenciacontable)
      end

      it "redirects to the refenciacontable" do
        refenciacontable = Refenciacontable.create! valid_attributes
        put :update, :id => refenciacontable.id, :refenciacontable => valid_attributes
        response.should redirect_to(refenciacontable)
      end
    end

    describe "with invalid params" do
      it "assigns the refenciacontable as @refenciacontable" do
        refenciacontable = Refenciacontable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Refenciacontable.any_instance.stub(:save).and_return(false)
        put :update, :id => refenciacontable.id.to_s, :refenciacontable => {}
        assigns(:refenciacontable).should eq(refenciacontable)
      end

      it "re-renders the 'edit' template" do
        refenciacontable = Refenciacontable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Refenciacontable.any_instance.stub(:save).and_return(false)
        put :update, :id => refenciacontable.id.to_s, :refenciacontable => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested refenciacontable" do
      refenciacontable = Refenciacontable.create! valid_attributes
      expect {
        delete :destroy, :id => refenciacontable.id.to_s
      }.to change(Refenciacontable, :count).by(-1)
    end

    it "redirects to the refenciacontables list" do
      refenciacontable = Refenciacontable.create! valid_attributes
      delete :destroy, :id => refenciacontable.id.to_s
      response.should redirect_to(refenciacontables_url)
    end
  end

end
